version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php
    networks:
      - caddy_php

  php:
    image: php:8.2-fpm-alpine
    volumes:
      - ./public:/var/www/html
    networks:
      - caddy_php

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy_php:
    driver: bridge